# Generated by Django 2.1.2 on 2019-02-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_on',
            field=models.IntegerField(default=0),
        ),
    ]
