# Generated by Django 2.1.2 on 2019-02-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190214_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='datetime',
            new_name='datetime_start',
        ),
        migrations.AddField(
            model_name='record',
            name='datetime_end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
