# Generated by Django 2.1.2 on 2019-02-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190214_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='datetime_end',
            new_name='dt_end',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='datetime_start',
            new_name='dt_start',
        ),
    ]
