# Generated by Django 2.1.2 on 2019-02-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20190215_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='listened',
            field=models.FloatField(default=0),
        ),
    ]
