# Generated by Django 2.1.2 on 2018-10-27 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('video_id', models.CharField(max_length=128)),
                ('channel_id', models.CharField(max_length=128)),
                ('channel_name', models.CharField(max_length=256)),
                ('created_data', models.DateTimeField(default=datetime.datetime(2018, 10, 27, 23, 1, 54, 305233))),
                ('thumbnails_url', models.CharField(max_length=256, null=True, verbose_name='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='UserPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2018, 10, 27, 23, 1, 54, 328156))),
                ('watched_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Podcast')),
            ],
        ),
    ]
