# Generated by Django 2.1.2 on 2018-10-27 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 20, 4, 37, 917587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpodcast',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 20, 4, 37, 941528, tzinfo=utc)),
        ),
    ]
