# Generated by Django 2.1.2 on 2018-10-27 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20181027_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpodcast',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
