# Generated by Django 2.1.2 on 2018-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20181027_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
