# Generated by Django 2.1.2 on 2018-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20181221_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
