# Generated by Django 2.1.2 on 2019-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_podcast_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpodcast',
            name='duration_listened',
            field=models.IntegerField(default=0),
        ),
    ]
